"""
Django settings for zohoinvoice project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import json

data = open('yellowant_app_credentials.json').read()
data_json = json.loads(data)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@0*%rxy-ni$@29885_-%@!+b!ovyw8nc1-u1*0b+gb&sy#(rp$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

app_name = os.environ.get("HEROKU_APP_NAME")
BASE_URL = "https://{}.herokuapp.com".format(app_name)
ALLOWED_HOSTS = ['*', '{}.herokuapp.com'.format(app_name)]

BASE_HREF = "/"
SITE_PROTOCOL = "http://"

DEV_ENV = os.environ.get('ENV', 'DEV')
if DEV_ENV == "DEV":
    ZOHO_CLIENT_ID = "1000.IYQNQDQXMBZX95094O1RZLUCNUWNUO"
    ZOHO_CLIENT_SECRET = "cd171a5ad424f39d9bfde1273d1aea382f69cfa561"
    BASE_URL = "https://96ba0191.ngrok.io"
    SITE_DOMAIN_URL = "ngrok.io"
elif DEV_ENV == "HEROKU":
    BASE_URL = "https://{}.herokuapp.com/".format(app_name)
    ZOHO_CLIENT_ID = os.environ.get('ZOHO_CLIENT_ID')
    ZOHO_CLIENT_SECRET = os.environ.get('ZOHO_CLIENT_SECRET')
    app_name = os.environ.get("HEROKU_APP_NAME")
    SITE_DOMAIN_URL = "herokuapp.com"

YELLOWANT_OAUTH_URL = "https://www.yellowant.com/api/oauth2/authorize/"
YELLOWANT_APP_ID = str(data_json['application_id'])
YELLOWANT_CLIENT_ID = str(data_json['client_id'])
YELLOWANT_CLIENT_SECRET = str(data_json['client_secret'])
YELLOWANT_VERIFICATION_TOKEN = str(data_json['verification_token'])
YELLOWANT_REDIRECT_URL = BASE_URL + "redirecturl/"

ZOHO_OAUTH_URL = "https://accounts.zoho.com/oauth/v2/auth?"
ZOHO_TOKEN_URL = "https://accounts.zoho.com/oauth/v2/token?"
ZOHO_REFRESH_TOKEN_URL = "https://accounts.zoho.com/oauth/v2/token/revoke?"
ZOHO_REDIRECT_URL = BASE_URL + "/zoho-redirecturl/"

ZOHO_ORGANIZATION_URL = "https://invoice.zoho.com/api/v3/organizations"
ZOHO_USER_URL = "https://invoice.zoho.com/api/v3/users"
ZOHO_CONTACT_URL = "https://invoice.zoho.com/api/v3/contacts"
ZOHO_ITEMS_URL = "https://invoice.zoho.com/api/v3/items"
ZOHO_CONTACT_PERSON_URL = "https://invoice.zoho.com/api/v3/contacts/contactpersons"
ZOHO_INVOICE_URL = "https://invoice.zoho.com/api/v3/invoices"
# Application definition

INSTALLED_APPS = [
    'lib.web',
    'lib.records',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zohoinvoice.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zohoinvoice.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'zohoinvoice',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '',
    }
}

if DEV_ENV == "HEROKU":
    import dj_database_url
    db_from_env = dj_database_url.config()
    DATABASES['default'].update(db_from_env)
    DATABASES['default']['CONN_MAX_AGE'] = 500

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

