"""
Django settings for zohoinvoice project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@0*%rxy-ni$@29885_-%@!+b!ovyw8nc1-u1*0b+gb&sy#(rp$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

BASE_URL = "http://37268bf7.ngrok.io"
ALLOWED_HOSTS = ["*"]
BASE_HREF = "/"

YELLOWANT_OAUTH_URL = "https://www.yellowant.com/api/oauth2/authorize/"
YELLOWANT_APP_ID = "1913"
YELLOWANT_CLIENT_ID = "jWLS868QSicCy6cCq3gyDbGQs1kS6ps1OtnUT8W2"
YELLOWANT_CLIENT_SECRET ="CWAMtAggmN9uCshvq8J1brsBeLZsOsi3KkEkfesh2QHxygLP7XGQ7iBnXcuvRdXMYVfS3xhuW8hXiBKMGYpHCup8XYagRTISerNmFvHuN7RUH9mKKigEuWF2IlyqRo5c"
YELLOWANT_VERIFICATION_TOKEN = "gLwR3J3vtb5IXbvgpP0igehNqdr40EHjU4X7MznLkJqzBlE78COsMtDjq2UryhOgV7Kkr9wQtpVRdeX20dspMwnOdMeQP4mrmZKMzXdDW6BS8PWFnORkBgO3cPcG8gJf"
YELLOWANT_REDIRECT_URL = BASE_URL + "/redirecturl/"


ZOHO_CLIENT_ID = "1000.IYQNQDQXMBZX95094O1RZLUCNUWNUO"
ZOHO_CLIENT_SECRET = "cd171a5ad424f39d9bfde1273d1aea382f69cfa561"

ZOHO_OAUTH_URL = "https://accounts.zoho.com/oauth/v2/auth?"
ZOHO_TOKEN_URL = "https://accounts.zoho.com/oauth/v2/token?"
ZOHO_REFRESH_TOKEN_URL = "https://accounts.zoho.com/oauth/v2/token/revoke?"
ZOHO_REDIRECT_URL = BASE_URL + "/zoho-redirecturl/"

ZOHO_ORGANIZATION_URL = "https://invoice.zoho.com/api/v3/organizations"
ZOHO_USER_URL = "https://invoice.zoho.com/api/v3/users"
ZOHO_CONTACT_URL = "https://invoice.zoho.com/api/v3/contacts"
ZOHO_ITEMS_URL = "https://invoice.zoho.com/api/v3/items"
ZOHO_CONTACT_PERSON_URL = "https://invoice.zoho.com/api/v3/contacts/contactpersons"
ZOHO_INVOICE_URL = "https://invoice.zoho.com/api/v3/invoices"
# Application definition

INSTALLED_APPS = [
    'lib.web',
    'lib.records',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zohoinvoice.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zohoinvoice.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'zohoinvoice',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
