# Generated by Django 2.0.2 on 2018-06-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoInvoiceUserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoho_access_token', models.TextField(max_length=200)),
                ('zoho_refresh_token', models.TextField(max_length=200)),
                ('user_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.YellowUserToken')),
            ],
        ),
    ]
