# Generated by Django 2.0.2 on 2018-06-21 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_zohoinvoiceusertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohoinvoiceusertoken',
            name='token_update',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
